export const benefits = [
  {
    id: "0",
    title: "NepaliGPT",
    description: "Advanced text generation for the Nepali language",
    text: "A cutting-edge GPT-2 based language model specifically designed for Nepali text generation. Trained on an extensive 9.3GB dataset from Nepali literature, news, and open-source content, this model excels at predicting contextually appropriate words in Nepali sentences. Built with modern deep learning techniques including optimized training parameters and bf16 precision for enhanced performance.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "1",
    title: "STEPS Parser",
    description: "Multilingual dependency parsing with transformer models",
    text: "A sophisticated research tool that analyzes sentence structures across multiple languages using advanced transformer models like mBERT and XLM-R. STEPS identifies grammatical relationships between words, making it invaluable for computational linguistics research. The system supports multiple languages, provides evaluation scripts, and enables reproducible research using Universal Dependencies data.",
    backgroundUrl: "./src/assets/benefits/card-2.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "2",
    title: "Nepali Named Entity Recognition",
    description:
      "Intelligent identification of people, places, and organizations in Nepali text",
    text: "A powerful NER model built on XLM-RoBERTa architecture, specifically trained on the Everest NER dataset for Nepali language processing. This tool automatically detects and categorizes important entities like person names, locations, and organizations in Nepali text. Easy to integrate with existing applications through the Hugging Face library, making it perfect for research and development projects.",
    backgroundUrl: "./src/assets/benefits/card-3.svg",
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
  },
  {
    id: "3",
    title: "NepaliLemmatizer",
    description:
      "Efficient root word extraction for Nepali language processing",
    text: "An intelligent lemmatization tool that converts inflected Nepali words to their root forms using advanced TRIE-based and hybrid algorithms. For example, it transforms 'खाएको' to its base form 'खानु'. This essential NLP tool streamlines text preprocessing for Nepali language applications, offering reliable and efficient word normalization for developers and researchers.",
    backgroundUrl: "./src/assets/benefits/card-4.svg",
    iconUrl: benefitIcon4,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "4",
    title: "Spoken Language Identifier",
    description: "Real-time audio language detection using deep learning",
    text: "An innovative CNN-based system that identifies spoken languages from audio clips using Mel Spectrogram analysis. Currently supports five South Asian languages: Nepali, Hindi, Sanskrit, Newari, and Maithili. The system processes audio files as short as 10 seconds and includes a web API for real-time predictions. Fully containerized with Docker for easy deployment and scalability.",
    backgroundUrl: "./src/assets/benefits/card-5.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "5",
    title: "COVID-19 Nepali Tweet Classifier",
    description: "AI-powered social media analysis for public health insights",
    text: "A specialized multilingual AI system that analyzes Nepali-language tweets about COVID-19, filling a critical gap in social media monitoring for low-resource languages. The system automatically categorizes tweets into eight key topics including symptoms, vaccination, and misinformation. Features a live dashboard powered by advanced mBERT and MuRIL models, with all datasets and code available as open-source resources.",
    backgroundUrl: "./src/assets/benefits/card-6.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
  },
];
