[phases.setup]
nixPkgs = ["python311", "gcc", "glibc"]

[phases.install]
cmd = "pip install -r requirements.txt"

[start]
cmd = "python app.py"

[variables]
PORT = "8000"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
